dist: xenial
sudo: required
language: python
python:
- '3.8'
- '3.9'
- '3.10'
- '3.11'
cache: pip
before_install:
- git submodule update --init
- git submodule status
install: pip install tox-travis
script: make tox
after_success:
- coveralls
stages:
- test
- deploy
jobs:
  include:
  - stage: deploy
    python: 3.8
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: ga4gh
      skip_upload_docs: true
      skip_cleanup: true
      distributions: bdist_egg bdist_wheel
      on:
        tags: true
        branch: develop
      password:
        secure: HWsxDri2EoC7+PBva7xU1EFFRFwukKBnTZ73fJnwdaJ/hpsGQHjS/OnlYNI+mm8RjCqEmOKr2O+fpd8ZCoDh8hWD+1DAwRlculxgt2stB3sjF+pG6+/It9MyWw6pdik0/t1kcmhzN7gFUgdgyekMFTnf4utYuv2rUljBjmExdZUQl4oGR01Zu7K71JuMSd+RGdvkznfTVtrXALTDz1yTQnBJpqgCLFcmzAn39yYwIcO/ysp4Er4+XpJOLvyzPYEc75wEQoMJY9O90wq3awEHcDMe7bdQDF5mf8pf6Cq2uynsYdt0LtHm/HpSVQfLQcHjANEuYXuBaPSrYl8M/epd0veFbGsWPpRuxE9PljRJzTPdR25GaqC6mODgoWQdCCt8sEj6JxPDM+O5SyUhJt7DpIggLB1ytI8lpxGHkXBRuLqVmcITitC8QbIKndVe0AezgQSDloDNRpsNvP677IXiyyTdNhqXtajTFxopsY62d5a5OQMgT5naC7VyyhQY5DAj5o5kcjowGBdA2dwpYRnWmE275hTvxfvF9iEBQOVFa/bxyKbvWBV00irb+XYNN6o1yuiINYRMLs6gwLwWc+mynY+I5Doo35IurRX2Em9c43mpQhf0h1P3XzSRY36e9aeuWcomcrwZy0Hoex/X8kzH/koac+7y2nAqsFkDvuf7EA4=
notifications:
  slack:
    secure: fjG0TJp71JAziHs3qaDI6ONHXC7C9XWwPfTTprRC60cD1u02ySwjPj1pFBqerQ6NPpgt3TuXWtl7NiGJiIfymoVh4To2eE1M5crY9FbQxbV/DCF7nJHtYy9EGvsqfCo+Z6maYnMeC5wyg6NxMyIDWg0QGhyjExU6NJRBGZFZ5XvP8qzx9Ig2oxvXYQWFzAbWQ1goxAxPQmsn1wlsPIIlIGqYZ5pSdLttvS4PDYq3NtLB59K4qGVm2br9spLuoK52YoBvl1K8U9rn8ImunY1p6FEG0lPuZbhgEV79oGxroH+wzIrnf4d/Nr+ztZbe5VLt+Lq+mG3SNWfKnyi4XQHe12NpnyFkiJwXIltmh8ZT/MLDFIqJ0+P89MBy0biW3OAlthSDzKW6ddO++1P0zv5BgFY5+1v3egoN879vMiStwFZOjj7lm91poiE0Ca7pmajSNqaPmSUCMEWN3B0vIQS32MhYKNTb3mOPHAIChIFX+vdAgVVryuN4y1X1JZLM0cPdvdkL/0zChnwsTzNCOWAa6C6dPrHAOvJvcBGtT1khLuE7AFTVclXcmQVKjENOgdK/3X7uiV01ECvwyPVxcRD+MjeYrWZ/F99a4vR31ere6CKgMEkKckfq7japfWWtaUCmXDhVhfiflDxTJW2vOqgERMj2S1bZeX2OBHOOL4kRM3c=
